version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - sqlite_data:/app/data # O arquivo db.sqlite será salvo neste volume

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front_restaurante
    ports:
      - "8080:80" 
    depends_on:
      - backend

volumes:
  sqlite_data: